---
driver:
  name: vagrant
  network:
  - ['forwarded_port', {guest: 4440, host: 4440, auto_correct: true}] # rundeck server port
  - ['forwarded_port', {guest: 9980, host: 9980, auto_correct: true}] # chef-rundeck port

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04

suites:
  - name: server
    run_list:
      - recipe[rundeck-server]

  - name: job
    attributes:
      rundeck_server:
        rundeck-config.framework:
          rundeck.tokens.file: '/etc/rundeck/token.properties'
    run_list:
      - recipe[rundeck-test]
