---
driver:
  name: vagrant
  network:
    - ['forwarded_port', {guest: 4440, host: 4440, auto_correct: true}] # rundeck server port
    - ['forwarded_port', {guest: 9980, host: 9980, auto_correct: true}] # chef-rundeck port

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.15.19

platforms:
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: server
    run_list:
      - recipe[rundeck-server]
      - recipe[rundeck-server::install_cli]

  - name: server-data_bag
    data_bags_path: 'test/data_bags'
    encrypted_data_bag_secret_key_path: "test/encrypted_data_bag_secret"
    run_list:
      - recipe[rundeck-server]
      - recipe[rundeck-server::install_cli]
    attributes:
      rundeck_server:
        data_bag:
          realm_user: rundeck_users
          cli_user: rundeck_cli

  - name: job
    attributes:
      rundeck_server:
        rundeck-config.framework:
          rundeck.tokens.file: '/etc/rundeck/token.properties'
    run_list:
      - recipe[rundeck-test]
