---
driver:
  name: vagrant
  network:
    - ['forwarded_port', {guest: 4440, host: 4440, auto_correct: true}] # rundeck server port
    - ['forwarded_port', {guest: 9980, host: 9980, auto_correct: true}] # chef-rundeck port

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.15.19

platforms:
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: server
    run_list:
      - recipe[rundeck-server]

  - name: server-2.7.x
    attributes:
      rundeck_server:
        jaas:
          - module: 'org.eclipse.jetty.jaas.spi.PropertyFileLoginModule'
            flag: 'required'
            options:
              debug: 'true'
              file: '/etc/rundeck/realm.properties'
        packages:
          rundeck: '2.7.1-1.25.GA'
          rundeck-config: '2.7.1-1.25.GA'
    run_list:
      - recipe[rundeck-server]
      - recipe[rundeck-server::install_cli]

  - name: job
    attributes:
      rundeck_server:
        rundeck-config.framework:
          rundeck.tokens.file: '/etc/rundeck/token.properties'
    run_list:
      - recipe[rundeck-test]
