name             'rundeck-test'
maintainer       'Robert Veznaver'
maintainer_email 'r.veznaver@criteo.com'
license          'Apache License 2.0'
description      ''
long_description ''
version          '0.1.0'
depends          'rundeck-server'
